# Generated by Django 4.2.16 on 2026-06-12 12:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "channel_preference",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("rcs", "RCS"),
                            ("auto", "Auto"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("rfm_recency_score", models.IntegerField(default=0)),
                ("rfm_frequency_score", models.IntegerField(default=0)),
                ("rfm_monetary_score", models.IntegerField(default=0)),
                ("rfm_composite", models.FloatField(default=0.0)),
                (
                    "rfm_tier",
                    models.CharField(db_index=True, default="Unscored", max_length=30),
                ),
                ("churn_risk_score", models.FloatField(default=0.0)),
                ("predicted_send_hour", models.IntegerField(default=10)),
                (
                    "ltv_estimate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "last_order_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("fulfilled", "Fulfilled"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_store", "In Store"),
                            ("app", "App"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("items", models.JSONField(default=list)),
                ("ordered_at", models.DateTimeField(db_index=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["rfm_tier", "-total_spend"],
                name="customers_c_rfm_tie_1ba6d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["-last_order_at"], name="customers_c_last_or_e8fcad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-ordered_at"],
                name="customers_o_custome_9cc824_idx",
            ),
        ),
    ]
