# Generated by Django 4.2.16 on 2026-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="product_category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
