# Generated by Django 4.2.16 on 2026-06-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
        ("segments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("rcs", "RCS"),
                            ("auto", "Auto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message_template", models.TextField()),
                ("ai_generated_copy", models.BooleanField(default=False)),
                (
                    "send_mode",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("scheduled", "Scheduled"),
                            ("multi_wave", "Multi-Wave"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("wave_config", models.JSONField(blank=True, null=True)),
                ("is_ab_test", models.BooleanField(default=False)),
                ("ab_variants", models.JSONField(default=list)),
                ("ab_winner_variant", models.CharField(blank=True, max_length=50)),
                ("ab_decided_at", models.DateTimeField(blank=True, null=True)),
                ("stat_total", models.IntegerField(default=0)),
                ("stat_sent", models.IntegerField(default=0)),
                ("stat_delivered", models.IntegerField(default=0)),
                ("stat_failed", models.IntegerField(default=0)),
                ("stat_opened", models.IntegerField(default=0)),
                ("stat_read", models.IntegerField(default=0)),
                ("stat_clicked", models.IntegerField(default=0)),
                ("stat_converted", models.IntegerField(default=0)),
                (
                    "stat_revenue_attributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("launched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=20)),
                ("message_body", models.TextField()),
                ("variant_label", models.CharField(blank=True, max_length=50)),
                (
                    "stub_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("opened", "Opened"),
                            ("read", "Read"),
                            ("clicked", "Clicked"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("retry_count", models.IntegerField(default=0)),
                ("converted", models.BooleanField(default=False)),
                ("conversion_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "conversion_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.order",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("opened", "Opened"),
                            ("read", "Read"),
                            ("clicked", "Clicked"),
                            ("converted", "Converted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("metadata", models.JSONField(default=dict)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaigns.communicationlog",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("rcs", "RCS"),
                            ("auto", "Auto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message_template", models.TextField()),
                ("use_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["campaign", "status"], name="campaigns_c_campaig_7450f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["customer", "-queued_at"], name="campaigns_c_custome_5251ce_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communicationevent",
            unique_together={("log", "event_type")},
        ),
    ]
